### ISSUE TITLE
SDK 4.0 - image_classification_networks - Build error with camera

### ISSUE THREAD

**Issue by antocad** [GreenWaves-Technologies/nn_menu#2]
configuration:
GAP8_V3
SDK 4.0

error:
When I go to this example: image_classification_networks
I want to use my camera Himax input (without lcd); so I change this line in the Makefile: HAVE_CAMERA?=1

but when I do 'make clean all run platform=board'
I have this error:
```
Graph constructor exited with error: 3
Traceback (most recent call last):
  File "/home/gap123/gap/gap_sdk/tools/gapy/gapy", line 162, in <module>
    main()
  File "/home/gap123/gap/gap_sdk/tools/gapy/gapy", line 152, in main
    operationFunc(args, config)
  File "/home/gap123/gap/gap_sdk/tools/gapy/run.py", line 157, in operationFunc
    raise RuntimeError('Runner has failed with value: %d' % status)
RuntimeError: Runner has failed with value: -1
make: *** [/home/gap123/gap/gap_sdk/tools/rules/pulp_rules.mk:244 : run] Erreur 1
```

PS: This error doesn't appear when I use HAVE_CAMERA?=0 with platform=gvsoc

How can I fix this please ?

**Comment by Pafrak** [comment]
Hi Antocad,
 I tried but I wasn't able to reproduce your problem. You can try to run

`make clean clean_model all run`

so that the generated model from NNtool is cleant and regenerated after changing makefile options.

Error 3 means that there was a problem allocating L2 memory. You can also try to decrease the L2 memory given to autotiler model changing the value of MODEL_L2_MEMORY in the makefile.

**Comment by antocad** [comment]
Hi Pafrak,

Thank you for your reply,
I changed the value of MODEL_L2_MEMORY (from 300000 to 200000) and it works now!
